#!/usr/bin/env node
/*
 * Precomputes the character graph layout and writes it to layout.js
 * (window.LAYOUT = { force: {id: [x, y]}, universe: {id: [x, y]} }).
 *
 * Why: laying the graph out in the browser meant ~140–200 synchronous force-simulation
 * ticks on page load — about 1.2 s of frozen main thread on a mid-range phone. The
 * simulation is deterministic, so it can run once here instead; phones then just place
 * the nodes (desktop still animates the force graph live, but starts from these positions
 * in the "By universe" view).
 *
 * The forces below MUST match buildCharGraph() / computeClusterCenters() in app.js. If you
 * change them there, change them here and re-run. Also re-run whenever characters or
 * links change — scripts/validate-data.js reports a stale layout.js.
 *
 *   node scripts/build-layout.js
 *
 * Uses the same d3 build the site loads (fetched from cdnjs), so no npm install is needed.
 */
const fs = require('fs');
const path = require('path');
const { ROOT, readData } = require('./data-io');

const D3_URL = 'https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js';
// keep in sync with app.js
const UNIVERSE_ORDER = ['Earth-199999', 'Earth-616', 'Earth-828', 'Earth-10005', 'Earth-96283', 'Earth-120703', 'Spider-Verse', 'Earth-688', 'Earth-838', 'Earth-89521', 'What-If', 'Beyond'];
const charRadius = d => Math.max(6, Math.min(24, 5 + Math.sqrt(d.degree || 1) * 3.6));

async function loadD3() {
  const res = await fetch(D3_URL);
  if (!res.ok) throw new Error(`could not download d3 (${res.status})`);
  const module = { exports: {} };
  new Function('module', 'exports', await res.text())(module, module.exports);
  return module.exports;
}

// deterministic stand-in for Math.random so the output only changes when the data does
function seeded(seed) {
  return () => { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; };
}

function clusterCenters(nodes) { // computeClusterCenters() with the viewport centre at (0, 0)
  const counts = {}; UNIVERSE_ORDER.forEach(u => counts[u] = 0);
  nodes.forEach(n => { if (counts[n.universe] != null) counts[n.universe]++; });
  const rad = {}; UNIVERSE_ORDER.forEach(u => { rad[u] = Math.max(130, 70 + Math.sqrt(counts[u] || 1) * 58); });
  const hub = 'Earth-199999', sats = UNIVERSE_ORDER.filter(u => u !== hub);
  const maxSat = Math.max(...sats.map(u => rad[u]));
  const R = Math.max(rad[hub] + maxSat + 230, sats.length * (2 * maxSat + 140) / (2 * Math.PI));
  const c = { [hub]: [0, 0, rad[hub]] };
  sats.forEach((u, i) => { const a = -Math.PI / 2 + (i / sats.length) * 2 * Math.PI; c[u] = [R * Math.cos(a), R * Math.sin(a), rad[u]]; });
  c._fallback = [0, 0, 200];
  return c;
}

function settle(sim) { // run to the simulation's own end (alpha < alphaMin), like d3 would on screen
  const n = Math.ceil(Math.log(sim.alphaMin()) / Math.log(1 - sim.alphaDecay()));
  sim.alpha(1).stop(); for (let i = 0; i < n; i++) sim.tick();
}

function positions(nodes) {
  const out = {};
  for (const n of nodes) out[n.id] = [Math.round(n.x), Math.round(n.y)];
  return out;
}

async function main() {
  const d3 = await loadD3();
  const DATA = readData();
  const fresh = () => ({
    nodes: DATA.characters.nodes.map(n => ({ id: n.id, universe: n.universe, degree: n.degree })),
    links: DATA.characters.edges.map(e => ({ source: e.source, target: e.target, type: e.type })),
  });

  // "Общий граф" (force)
  const f = fresh();
  settle(d3.forceSimulation(f.nodes)
    .force('link', d3.forceLink(f.links).id(d => d.id).distance(l => 72 + (l.type === 'team' ? 14 : 0)).strength(0.28))
    .force('charge', d3.forceManyBody().strength(-320))
    .force('center', d3.forceCenter(0, 0))
    .force('x', d3.forceX(0).strength(0.03))
    .force('y', d3.forceY(0).strength(0.03))
    .force('collision', d3.forceCollide().radius(d => charRadius(d) + 11).strength(0.9)));

  // "По вселенным" (universe clusters)
  const u = fresh();
  const centers = clusterCenters(u.nodes);
  const rnd = seeded(20260930);
  const cOf = d => centers[d.universe] || centers._fallback;
  u.nodes.forEach(n => { const c = cOf(n); n.x = c[0] + (rnd() - 0.5) * c[2] * 1.2; n.y = c[1] + (rnd() - 0.5) * c[2] * 1.2; });
  settle(d3.forceSimulation(u.nodes)
    .force('link', d3.forceLink(u.links).id(d => d.id).distance(64).strength(l => l.type === 'variant' ? 0.008 : 0.12))
    .force('charge', d3.forceManyBody().strength(-260))
    .force('x', d3.forceX(d => cOf(d)[0]).strength(0.16))
    .force('y', d3.forceY(d => cOf(d)[1]).strength(0.16))
    .force('collision', d3.forceCollide().radius(d => charRadius(d) + 14).strength(0.95)));

  const js = '/* generated by scripts/build-layout.js — do not edit by hand */\n'
    + 'window.LAYOUT=' + JSON.stringify({ force: positions(f.nodes), universe: positions(u.nodes) }) + ';\n';
  fs.writeFileSync(path.join(ROOT, 'layout.js'), js, 'utf8');
  console.log(`layout.js: ${f.nodes.length} characters, ${(js.length / 1024).toFixed(1)} KB`);
}
main().catch(e => { console.error(e); process.exit(1); });
